datasets:
  use_data: [ 'depth_vel', 'migrated_image', 'well_log', 'horizon', 'rms_vel' ] # ('model', 'time_vel', 'migrate', 'well_log', 'horizens', 'rms_vel')
  dataset_name: [ 'FlatVelA', 'FlatVelB', 'CurveVelA', 'CurveVelB' ]
  use_normalize: '-1_1'  # '01' '-1_1'
  depth_velocity:
    shape: [ 1, 70, 70 ]

sv_inv_net:
  base_channel: 16
  condition_channel: 16

training:
  lr: 1e-4
  perceptual_weight: 0
  ssim_weight: 0
  use_ema: True
  gradient_clip_val: None

  max_epochs: 100
  min_epochs: 50
  device: [ 0, ]
  precision: 'bf16-mixed'

  dataloader:
    batch_size: 100
    num_workers: 2
    prefetch_factor: 3

  logging:
    log_dir: 'logs/baselines/sv_inv_net/'
    log_version: ''

  callbacks:
    early_stopping:
      monitor: 'val/mse'
      mode: 'min'
      patience: 10

    checkpoint:
      filename: 'epoch_{epoch}-ssim{val/ssim:.3f}'
      save_top_k: 3
      monitor: 'val/ssim'
      mode: 'max'

testing:
  test_save_dir: 'logs/baseline/sv_inv_net'
  ckpt_path: ''